const menu=document.querySelector('.menu-toggle');const nav=document.getElementById('navigation');if(menu&&nav){menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}})}

// Keep the homepage fully patient-facing: no CV links or CV teaser.
document.querySelectorAll('a[href="professional.html"]').forEach(a=>a.remove());document.querySelector('.professional-teaser')?.remove();

// Force the supplied portrait to be a major visual element.
const heroImg=document.querySelector('.hero-photo img');if(heroImg){heroImg.loading='eager';heroImg.fetchPriority='high';heroImg.style.cssText='width:100%;height:100%;display:block;object-fit:cover;object-position:center 10%;position:relative;z-index:1';}

// Strong, premium visual differentiation for the first clinical cards.
const cardThemes=['clinical-blue','clinical-teal','clinical-gold','clinical-violet','clinical-sky','clinical-rose'];document.querySelectorAll('.specialty-card').forEach((card,i)=>{card.classList.add(cardThemes[i%6]);const p=card.querySelector('p');if(p&&!card.querySelector('.card-label')){const label=document.createElement('span');label.className='card-label';label.textContent=['المفاصل','المفاصل','تأهيل وحركة','إصابات معقدة','إعادة بناء','جراحات تصحيحية'][i];card.insertBefore(label,card.querySelector('h3'))}});

// The causes item was previously only a placeholder. Make it visually explicit and link to the preserved video coverage.
const causesCard=[...document.querySelectorAll('.media-card')].find(c=>c.textContent.includes('أسباب خشونة الركبة'));if(causesCard){causesCard.classList.add('causes-video-card');const ph=causesCard.querySelector('.media-placeholder');if(ph)ph.innerHTML='<div class="video-poster"><span class="play-mark">▶</span><strong>أسباب خشونة الركبة</strong><small>النوع الأولي والثانوي</small></div>';const link=causesCard.querySelector('a');if(link){link.textContent='شاهد الفيديو والتغطية ←';link.classList.add('prominent-link')}}

// Inject final presentation overrides without touching the base stylesheet.
const style=document.createElement('style');style.textContent=`
.hero-photo{background:#102f52!important;min-height:560px}.hero-photo>img{opacity:1!important;visibility:visible!important}.photo-shade{z-index:2}.hero-caption{z-index:3}.floating-card{z-index:4}
.trust-strip .wrap{justify-content:center;gap:48px}.specialty-card{border:0!important;box-shadow:0 16px 42px rgba(15,44,89,.10)!important;min-height:330px}.specialty-card .icon{width:64px;height:64px;border-radius:18px;display:grid;place-items:center;color:#fff!important;margin:18px 0;background:#0F2C59}.specialty-card h3{font-size:23px}.specialty-card p{color:#465d6d;font-size:16px}.card-label{display:inline-flex;padding:5px 10px;border-radius:999px;font-size:11px;font-weight:900;margin-bottom:10px;background:rgba(255,255,255,.8);color:#0F2C59}.clinical-blue{background:linear-gradient(145deg,#eaf6ff,#d9ecfb)!important;border-top:5px solid #176b9c!important}.clinical-teal{background:linear-gradient(145deg,#e8f8f4,#d7efe8)!important;border-top:5px solid #17806d!important}.clinical-gold{background:linear-gradient(145deg,#fff8e5,#f7e9bd)!important;border-top:5px solid #c29528!important}.clinical-violet{background:linear-gradient(145deg,#f3efff,#e6ddfb)!important;border-top:5px solid #7156a5!important}.clinical-sky{background:linear-gradient(145deg,#eef6ff,#dfeafa)!important;border-top:5px solid #3f6fa7!important}.clinical-rose{background:linear-gradient(145deg,#fff0f3,#f7dde4)!important;border-top:5px solid #a9526b!important}.clinical-teal .icon{background:#17806d}.clinical-gold .icon{background:#b78a24}.clinical-violet .icon{background:#7156a5}.clinical-sky .icon{background:#3f6fa7}.clinical-rose .icon{background:#a9526b}.more{font-size:14px;text-decoration:underline;text-underline-offset:5px}
.why-card{border-top:5px solid #176b9c!important}.why-card:nth-child(2){border-top-color:#c29528!important}.why-card:nth-child(3){border-top-color:#17806d!important}.why-card.featured{border-top:5px solid #d4af37!important}.science-card{min-height:210px;box-shadow:0 12px 34px rgba(15,44,89,.08);border:0!important}.science-card:nth-child(1){background:#eaf6ff}.science-card:nth-child(2){background:#e8f8f4}.science-card:nth-child(3){background:#fff8e5}.science-card:nth-child(4){background:#f3efff}.science-feature{border-top:6px solid #d4af37}.media-card{box-shadow:0 16px 44px rgba(15,44,89,.10)}.causes-video-card{border-top:5px solid #d4af37}.video-poster{width:100%;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;background:radial-gradient(circle at 50% 35%,#245b7c,#102c4b);color:#fff;text-align:center}.video-poster strong{font-size:18px}.video-poster small{font-size:12px;color:#dbe9f1}.play-mark{display:grid;place-items:center;width:48px;height:48px;border-radius:50%;background:#d4af37;color:#0f2c59;font-size:18px;padding-left:3px}.prominent-link{display:inline-flex!important;margin-top:14px;padding:10px 15px!important;border:0!important;border-radius:9px;background:#0f2c59;color:#fff!important}.contact-actions a{border:1px solid rgba(255,255,255,.35)}
@media(max-width:860px){.hero-photo{min-height:430px}.specialty-card{min-height:300px}.trust-strip .wrap{gap:16px}}
`;document.head.appendChild(style);

const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();const items=document.querySelectorAll('.reveal');if('IntersectionObserver' in window){const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});items.forEach(i=>observer.observe(i))}else items.forEach(i=>i.classList.add('visible'));
